---
abstract: 'Moose based MARC records set of tools'
author:
  - 'Frederic Demians <f.demians@tamil.fr>'
build_requires:
  MARC::File::XML: 0
  Module::Build: 0.3601
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: marc-moose
requires:
  Carp: 0
  JSON: 0
  MARC::Record: 0
  Moose: 1.00
  Moose::Util::TypeConstraints: 0
  Text::Iconv: 1.7
  XML::SAX: 0
  XML::SAX::Base: 0
  XML::Simple: 0
  XML::Writer: 0.606
  YAML: 0
  YAML::Syck: 0
  namespace::autoclean: 0
  overload: 0
version: 0.018
