---
abstract: 'MARC bibliographic records set of tools'
author:
  - 'Frédéric Demians <f.demians@tamil.fr>'
build_requires:
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marc
requires:
  Carp: 0
  Moose: 1.00
  Moose::Util::TypeConstraints: 0
  Text::Iconv: 1.7
  XML::Writer: 0.606
  YAML: 0
  namespace::autoclean: 0
  overload: 0
version: 0.001
